# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.8'

services:

  hdc3a-mock-services:
    container_name: 'hdc3a-mock-services'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    tty: true
    volumes:
      # App
      - './:/home/appuser'
      # Logs
      - './logs:/home/appuser/logs'
    env_file:
      - '.env'
