# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`
version: '3.9'

services:
  app:
   image: registry.lts.harvard.edu/lts/hdc3a-mock-services:1.0.1
   build:
     context: .
     dockerfile: Dockerfile

